name: "Database Migrations"
description: "Make database migrations using flyway and an ssh connection for PostgreSQL"
inputs:
  flyway_version:
    description: "Flyway version"
    required: false
    default: '8.5.11'
  ssh_key:
    description: ssh key
    required: true
  ssh_host:
    description: ssh host
    required: true
  ssh_user:
    description: ssh username
    required: true
  db_host:
    description: database host
    required: true
  db_user:
    description: database user
    required: true
  db_password:
    description: database password
    required: true
  db_port:
    description: database port
    required: false
    default: '5432'
  db_name:
    description: database name
    required: true
  migrations_folder_path:
    description: Path from repository root to the database migrations folder
    required: false
    default: 'db/migrations'
  flyway_config_path:
    description: Path from repository root folder to the flyway config file
    required: false
    default: 'db/conf/flyway.conf'
  flyway_extra_params:
    description: Add extra params to Flyway command. By defaults, it adds -outOfOrder=true
    required: false
    default: '-outOfOrder=true -ignoreMigrationPatterns=*:missing'
  flyway_command:
    description: 'Command to run. Ej: migrate, repair'
    required: false
    default: 'migrate'
runs:
  using: "composite"
  steps:
    - name: Cache Flyway binary
      uses: actions/cache@v3
      with:
        path: flyway-${{inputs.flyway_version}}
        key: flyway-${{inputs.flyway_version}}-linux-x64

    - name: Install Flyway (if not cached)
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        FLYWAY_VERSION: ${{inputs.flyway_version}}
      run: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$FLYWAY_VERSION/flyway-commandline-$FLYWAY_VERSION-linux-x64.tar.gz | tar xvz

    - name: Configure Flyway
      shell: bash
      env:
        FLYWAY_VERSION: ${{inputs.flyway_version}}
      run: sudo ln -s `pwd`/flyway-$FLYWAY_VERSION/flyway /usr/local/bin

    - name: Configure SSH
      shell: bash
      env:
        SSH_HOST: ${{inputs.ssh_host}}
        SSH_KEY: ${{inputs.ssh_key}}
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        touch ~/.ssh/ssh_key.pem
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        eval `ssh-agent -s`
        ssh-add - <<< "$SSH_KEY"
        echo "$SSH_KEY" >> ~/.ssh/ssh_key.pem
        chmod  400 ~/.ssh/ssh_key.pem

    - name: SSH connection
      shell: bash
      env:
        DB_HOST: ${{inputs.db_host}}
        DB_PORT: ${{inputs.db_port}}
        SSH_USER: ${{inputs.ssh_user}}
        SSH_HOST: ${{inputs.ssh_host}}
      run: |
        ssh -o ExitOnForwardFailure=yes -f -N -L 5432:$DB_HOST:$DB_PORT \
          $SSH_USER@$SSH_HOST -i ~/.ssh/ssh_key.pem

    - name: Make migrations
      shell: bash
      env:
        FLYWAY_COMMAND: ${{inputs.flyway_command}}
        DB_NAME: ${{inputs.db_name}}
        FLYWAY_EXTRA_PARAMS: ${{inputs.flyway_extra_params}}
        DB_USER: ${{inputs.db_user}}
        DB_PASSWORD: ${{inputs.db_password}}
        MIGRATIONS_FOLDER_PATH: ${{inputs.migrations_folder_path}}
        FLYWAY_CONFIG_PATH: ${{inputs.flyway_config_path}}
      run: |
        flyway $FLYWAY_COMMAND -url=jdbc:postgresql://localhost:5432/$DB_NAME $FLYWAY_EXTRA_PARAMS \
          -user=$DB_USER \
          -password=$DB_PASSWORD \
          -locations=$MIGRATIONS_FOLDER_PATH \
          -configFiles=$FLYWAY_CONFIG_PATH
