name: "Database Migrations"
description: "Make database migrations using flyway and an ssh connection for PostgreSQL"
inputs:
  ssh_key:
    description: ssh key
    required: true
  ssh_host:
    description: ssh host
    required: true
  ssh_user:
    description: ssh username
    required: true
  db_host:
    description: database host
    required: true
  db_user:
    description: database user
    required: true
  db_password:
    description: database password
    required: true
  db_port:
    description: database port
    required: false
    default: '5432'
  db_schema:
    description: database schema
    required: false
    default: 'public'
  path_to_migrations_folder:
    description: Path from repository root to the database migrations folder
    required: false
    default: 'db/migrations'
  path_to_flyway_config:
    description: Path from migrations foldert to the flyway config file
    required: false
    default: 'conf/flyway.conf'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Flyway
      shell: bash
      run: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.11/flyway-commandline-8.5.11-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-8.5.11/flyway /usr/local/bin 
    - name: Configure SSH
      shell: bash
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/known_hosts
        touch ~/.ssh/ssh_key.pem
        ssh-keyscan -H ${{inputs.ssh_host}} >> ~/.ssh/known_hosts
        eval `ssh-agent -s`
        ssh-add - <<< "${{inputs.ssh_key}}"
        echo "${{inputs.ssh_key}}" >> ~/.ssh/ssh_key.pem
        chmod  400 ~/.ssh/ssh_key.pem
    - name: SSH connection
      shell: bash
      run: ssh -o ExitOnForwardFailure=yes -f -N -L 5432:${{inputs.db_host}}:${{inputs.db_port}} ${{inputs.ssh_user}}@${{inputs.ssh_host}} -i ~/.ssh/ssh_key.pem
      #run: ssh -fN -v -L 5432:${{inputs.db_host}}:${{inputs.db_port}} ${{inputs.ssh_user}}@${{inputs.ssh_host}}
    - name: Make migrations
      shell: bash
      run: flyway migrate -url=jdbc:postgresql://localhost:5432/${{inputs.db_schema}} \
        -user=${{inputs.db_user}} \
        -password=${{inputs.db_password}} \
        -locations={{inputs.path_to_migrations_folder}} \
        -configFiles={{inputs.path_to_flyway_config}}
    - name: Terminate SSH Tunnel
      shell: bash
      run: ps -o pid,cmd|grep "ssh -L"|grep -v grep|awk '{print $1}'|xargs kill

